version: "3.8"
services:
  cultum:
    container_name: cultum
    hostname: cultum
    restart: always
    networks:
      prism:
        ipv4_address: 172.25.36.69
    ports:
      - 80:80
    volumes:
      - ./lux/cultum/config.yml:/opt/cultum/config.yml
    build: ./cultum
  thaldrin:
    build: .
    container_name: thaldrin
    hostname: cadaver
    depends_on:
      - cultum
    restart: always
    networks:
      prism:
        ipv4_address: 172.25.36.21
    volumes:
      - ./config.ts:/opt/thaldrin/config.ts

networks:
  prism:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.36.0/24
