version: "3.8"
services:
  prometheus:
    container_name: prometheus
    build: ./lantern/prometheus
    restart: always
    networks:
      - lantern
    ports:
      - 9090:9090
  bot:
    container_name: thaldrin
    restart: always
    build: .
    ports:
      - 3621:3621
    depends_on:
      - prometheus
    volumes:
      - ./config.ts:/opt/thaldrin/config.ts
    networks:
      - lantern
      - default
networks:
  lantern:
